// <auto-generated />
using System;
using DreamyDiapersWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamyDiapersWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227172350_RemoveCart")]
    partial class RemoveCart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CartId");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Our teddy bear sets the standard for supreme softness and unmatched quality. Made from top-tier materials, its velvety fur invites you into a world of comfort. Experience the pinnacle of plush perfection with this exceptional cuddle companion.",
                            Name = "Supreme Soft Teddy Bear",
                            OriginalPrice = 15m,
                            Price = 15m,
                            Stock = 20,
                            Url = "Pictures/Items/TeddyBear.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enhance your baby's first steps with our Wooden Walker. Immerse your little one in the charm of nature as they take confident strides with this meticulously crafted wooden stroller. Designed for comfort and security, our eco-conscious Wooden Walker ensures a stylish and enjoyable outdoor experience for both you and your baby. Let every step be a delightful journey with the essence of nature guiding the way.",
                            Name = "Wooden Walker",
                            OriginalPrice = 45.99m,
                            Price = 42.99m,
                            Stock = 340,
                            Url = "Pictures/Items/WoodenWalker.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dr. Brown's baby Bottle ensures a natural flow for your baby's feeding journey. Designed with a focus on mimicking breastfeeding, these bottles promote a seamless transition and offer a comforting experience, making mealtime a joy for both baby and parent.",
                            Name = "Dr. Brown's Baby Bottle",
                            OriginalPrice = 9.99m,
                            Price = 8m,
                            Stock = 89,
                            Url = "Pictures/Items/Bottle.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Keep it together with our versatile clips. Ideal for securing blankets, toys, or stroller accessories, these clips add convenience to your parenting journey.",
                            Name = "Versatile Baby Clips",
                            OriginalPrice = 1.29m,
                            Price = 1.29m,
                            Stock = 50,
                            Url = "Pictures/Items/Clips.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Soothe your little one with our pacifier set. Designed for comfort and style, these pacifiers offer a calming experience for your baby.",
                            Name = "Pacifier Set",
                            OriginalPrice = 4.59m,
                            Price = 4.59m,
                            Stock = 0,
                            Url = "Pictures/Items/Pacifiers.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Facilitate efficient drying of your baby bottles with our purpose-built drying rack. Its smart design allows for easy arrangement and quick air-drying after washing.",
                            Name = "Baby Bottle Drying Rack",
                            OriginalPrice = 12m,
                            Price = 9m,
                            Stock = 25,
                            Url = "Pictures/Items/BottleDryingRack.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Make on-the-go napping a breeze with our travel crib. Compact and comfortable, this crib provides a cozy space for your baby to rest during your adventures.",
                            Name = "Portable Travel Crib",
                            OriginalPrice = 69.99m,
                            Price = 69.99m,
                            Stock = 16,
                            Url = "Pictures/Items/TravelCrib.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Create a safe and playful environment for your little one with our play yard. Easy to set up and fold, it's the perfect solution for indoor and outdoor playtime.",
                            Name = "Play Yard",
                            OriginalPrice = 99m,
                            Price = 89m,
                            Stock = 25,
                            Url = "Pictures/Items/PlayYard.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Support your baby's first steps with our sturdy walker. Designed for stability and fun, it encourages mobility and exploration in a safe environment.",
                            Name = "Baby's First Walker",
                            OriginalPrice = 49.99m,
                            Price = 44.99m,
                            Stock = 34,
                            Url = "Pictures/Items/Walker.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Navigate the streets with ease using our double stroller. Featuring a sleek red design and spacious seating, it's perfect for parents with two little ones.",
                            Name = "Red Double Stroller",
                            OriginalPrice = 229m,
                            Price = 229m,
                            Stock = 12,
                            Url = "Pictures/Items/Stroller.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dress your baby in comfort and style with our white onesie. Made from soft, breathable fabric, it's perfect for everyday wear and cuddle time.",
                            Name = "Cozy White Onesie",
                            OriginalPrice = 89m,
                            Price = 89m,
                            Stock = 13,
                            Url = "Pictures/Items/Onesie.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Stay organized on the go with our cute backpack. Let your little one's imagination soar with our adorable butterfly-shaped backpack. This cutie yellow backpack is not only stylish but also designed with comfort and convenience in mind.",
                            Name = "Yellow Butterfly Backpack",
                            OriginalPrice = 12m,
                            Price = 12m,
                            Stock = 14,
                            Url = "Pictures/Items/Backpack.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ensure your baby's safety with our set of aid bands. Adjustable and comfortable, these bands offer peace of mind during everyday activities.",
                            Name = "Safety Aid Bands Set",
                            OriginalPrice = 1.99m,
                            Price = 0.99m,
                            Stock = 0,
                            Url = "Pictures/Items/AidBands.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Entertain and stimulate your baby's senses with our charming rattle. Crafted for tiny hands, this delightful toy encourages early development.",
                            Name = "Stimulating Baby Rattle",
                            OriginalPrice = 4.99m,
                            Price = 3.99m,
                            Stock = 50,
                            Url = "Pictures/Items/Rattle.jpg"
                        });
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Cart", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Item", null)
                        .WithMany("Carts")
                        .HasForeignKey("ItemId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.CartItem", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("CartItems")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Order", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Item", null)
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.Navigation("Address");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamyDiapersWebApp.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DreamyDiapersWebApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Item", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DreamyDiapersWebApp.Data.ApplicationUser", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
